language: ruby
rvm:
  - 2.3.3
services:
  - redis-server
script:
  - bundle exec rake spec
before_install:
  - cp config/database.yml.sample config/database.yml
  - psql -c 'create database idrop_test;' -U postgres
