# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a4c08fe45faa831700c0256456c38b4b9472df9c1eb41f143c63ed56c1b2cdea95e45c70d8f50eb85899eab965bd827ebe6907f2d918068b33ed1ec8d3768d7
  omniauth:
    facebook:
      app_id: '861409627287539'
      app_secret: '4ae169c007b68cabff7209ecee2c116c'

test:
  secret_key_base: 530b41b25bb16ae8cf50d80ff7ba3616aaa671263e227466686f935f75795eeadfa8186fb561cea2030da305cc4412a90a5e079ff0cac91d2bb694793074c9cd
  omniauth:
    facebook:
      app_id: '861409627287539'
      app_secret: '4ae169c007b68cabff7209ecee2c116c'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth:
    facebook:
      app_id: '861409627287539'
      app_secret: '4ae169c007b68cabff7209ecee2c116c'
