# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

series = Category.create(name: 'Seriado')
Candidate.create( name: "Game of Thrones", nickname: "Game of Thrones", image_url: "http://educativafm.com.br/novo/wp-content/uploads/2015/04/GAME-OF-THRONES.jpg", categories:[series])
Candidate.create( name: "Breaking Bad", nickname: "Breaking Bad", image_url: "http://www.obaoba.com.br/system/pictures/2013/8/266325/cropped/series11.png", categories:[series])
Candidate.create( name: "Supernatural", nickname: "Supernatural", image_url: "http://www.portalfamosos.com.br/wp-content/uploads/2015/07/supernatural.jpg", categories:[series])
Candidate.create( name: "Demolidor", nickname: "Demolidor", image_url: "http://cinepop.com.br/wp-content/uploads/2015/04/demolidoruniforme.jpg", categories:[series])
Candidate.create( name: "Friends", nickname: "Friends", image_url: "http://img10.deviantart.net/c456/i/2010/148/c/e/friends___central_perk_by_mariomj71099.jpg", categories:[series])
Candidate.create( name: "Sherlock", nickname: "Sherlock", image_url: "http://br.web.img2.acsta.net/pictures/14/01/06/14/35/382626.jpg", categories:[series])
Candidate.create( name: "The Originals", nickname: "The Originals", image_url: "http://theoriginalsaaf.com/wp-content/uploads/2014/07/ipad_originals_cast_768_1024.jpg", categories:[series])
Candidate.create( name: "Arrow", nickname: "Arrow", image_url: "https://upload.wikimedia.org/wikipedia/pt/f/fd/Arrow_(elenco).jpg", categories:[series])
Candidate.create( name: "Teen Wolf", nickname: "Teen Wolf", image_url: "http://www.gstatic.com/tv/thumb/tvbanners/8629851/p8629851_b_v7_ac.jpg", categories:[series])
Candidate.create( name: "House", nickname: "House", image_url: "http://pre13.deviantart.net/c716/th/pre/f/2015/148/5/e/dr__house__wallpaper_3__by_11kaito11-d52cuac.jpg", categories:[series])
Candidate.create( name: "The Flash", nickname: "The Flash", image_url: "http://www.gstatic.com/tv/thumb/tvbanners/10781465/p10781465_b_v7_ab.jpg", categories:[series])
Candidate.create( name: "The Walking Dead", nickname: "The Walking Dead", image_url: "http://www.obaoba.com.br/system/pictures/2013/8/266329/cropped/series14.jpg", categories:[series])
Candidate.create( name: "Grey's Anatomy", nickname: "Grey's Anatomy", image_url: "http://www.entertainmentwallpaper.com/images/desktops/movie/tv_grey_s_anatomy04.jpg", categories:[series])
Candidate.create( name: "How I Met Your Mother", nickname: "How I Met Your Mother", image_url: "http://www.dvdsreleasedates.com/covers/how-i-met-your-mother-the-complete-seventh-season-dvd-cover-67.jpg", categories:[series])
Candidate.create( name: "Os Simpsons", nickname: "Os Simpsons", image_url: "http://veja.abril.com.br/blog/temporadas/files/2015/05/Simpsons.jpg", categories:[series])
Candidate.create( name: "House of Cards", nickname: "House of Cards", image_url: "http://tribzap2it.files.wordpress.com/2014/01/house-of-cards-season-2-poster.jpg", categories:[series])
Candidate.create( name: "Once Upon A Time", nickname: "Once Upon A Time", image_url: "http://static.omelete.uol.com.br/media/extras/conteudos/once-upon-a-time-destaque.jpg", categories:[series])
Candidate.create( name: "Prison Break", nickname: "Prison Break", image_url: "http://ahoradofilme.com.br/wp-content/uploads/2015/06/prison-break.jpg", categories:[series])
Candidate.create( name: "The Vampire Diaries", nickname: "The Vampire Diaries", image_url: "http://s.sidereel.com/tv_shows/36981/giant_2x/Vampire-Diaries-S5-vsc.jpg", categories:[series])
Candidate.create( name: "The Big Bang Theory", nickname: "The Big Bang Theory", image_url: "http://www.fulldead.com.br/artista/uploads/subgenero/the-big-bang-theory--201503051503271.jpg", categories:[series])
Candidate.create( name: "Sense8", nickname: "Sense8", image_url: "http://cdn.fstatic.com/public/movies/covers/2015/05/thumbs/sense8-1a-temporada_t92039_c5LtivX_jpg_290x478_upscale_q90.jpg", categories:[series])
Candidate.create( name: "Pretty Little Liars", nickname: "Pretty Little Liars", image_url: "http://img3.wikia.nocookie.net/__cb20131222015802/glee/images/9/93/Pretty-Little-Liars-at-Chairs.jpg", categories:[series])
Candidate.create( name: "Orange Is The New Black", nickname: "Orange Is The New Black", image_url: "http://topfilmesonlinehd.com/wp-content/uploads/2015/03/series_34_Orange-Is-the-New-Black.jpg", categories:[series])
Candidate.create( name: "True Detective", nickname: "True Detective", image_url: "http://cdn.fstatic.com/public/movies/covers/2013/10/thumbs/true-detective-1a-temporada_t76295_jpg_290x478_upscale_q90.jpg", categories:[series])
Candidate.create( name: "Vikings", nickname: "Vikings", image_url: "http://www.gstatic.com/tv/thumb/tvbanners/9155926/p9155926_b_v7_ae.jpg", categories:[series])
Candidate.create( name: "Gotham", nickname: "Gotham", image_url: "http://omundodekappa.com.br/wp-content/uploads/2015/05/Gotham.jpg", categories:[series])
Candidate.create( name: "Forever", nickname: "Forever", image_url: "http://www.amanhaeuteconto.com.br/wp-content/uploads/2014/10/forever-serie.jpg", categories:[series])
Candidate.create( name: "Dexter", nickname: "Dexter", image_url: "http://www.obaoba.com.br/system/pictures/2013/8/266327/cropped/series13.png", categories:[series])
Candidate.create( name: "How To Get Away With Murder", nickname: "How To Get Away With Murder", image_url: "http://www.guiadeseriados.com.br/wp-content/uploads/2015/02/how-to-get-away-with-murder-1.jpg", categories:[series])
Candidate.create( name: "Penny Dreadful", nickname: "Penny Dreadful", image_url: "http://mb.web.sapo.io/bef6fe6c02ab5beaf0a6c4599ad8b776a9218874.jpg", categories:[series])

Election.create(description: 'Qual é a melhor série?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: series)

categoria = Category.create(name: 'Atriz')
Candidate.create( name: "Bruna Marquezine", nickname: "Bruna Marquezine", image_url: "http://s2.glbimg.com/6RYvaX2vHiyPNyBCNxRQzmHjKlA=/e.glbimg.com/og/ed/f/original/2015/06/17/bruna.jpg", categories:[categoria])
Candidate.create( name: "Ana Paula Arozio", nickname: "Ana Paula Arozio", image_url: "http://www.revistabula.com/wp/wp-content/uploads/2013/11/Ana-Paula-Ar%C3%B3sio.jpg", categories:[categoria])
Candidate.create( name: "Taís Araújo", nickname: "Taís Araújo", image_url: "http://www.revistabula.com/wp/wp-content/uploads/2013/11/Ana-Paula-Ar%C3%B3sio.jpg", categories:[categoria])
Candidate.create( name: "Maria Fernanda Cândido", nickname: "Maria Fernanda Cândido", image_url: "http://www.revistabula.com/wp/wp-content/uploads/2013/11/Maria-Fernanda-C%C3%A2ndido.jpg", categories:[categoria])
Candidate.create( name: "Gisele Bündchen", nickname: "Gisele Bündchen", image_url: "http://www.revistabula.com/wp/wp-content/uploads/2013/11/Gisele-Bundchen.jpg", categories:[categoria])
Candidate.create( name: "Luana Piovani", nickname: "Luana Piovani", image_url: "http://www.revistabula.com/wp/wp-content/uploads/2013/11/luanapiovani.jpg", categories:[categoria])
Candidate.create( name: "Flávia Alessandra", nickname: "Flávia Alessandra", image_url: "http://s.glbimg.com/et/nv/f/original/2011/05/02/naomi-620-465.jpg", categories:[categoria])
Candidate.create( name: "Paola Oliveira", nickname: "Paola Oliveira", image_url: "http://wp.clicrbs.com.br/atlantidacriciuma/files/2012/01/Paola-Oliveira-Divulga%C3%A7%C3%A3o.jpg", categories:[categoria])
Candidate.create( name: "Grazi Massafera", nickname: "Grazi Massafera", image_url: "http://3.bp.blogspot.com/-uGti_rZhFlE/Tgnl1tFu0GI/AAAAAAAABJY/B75ok7C3Pv4/s1600/Ed-161-PG-07-02-Grazi-Massafera.jpg", categories:[categoria])
Candidate.create( name: "Isis Valverde", nickname: "Isis Valverde", image_url: "http://novaslistas.com.br/system/items/000/201/898/original/isis.jpg?1386021095", categories:[categoria])
Candidate.create( name: "Sophia Abrahão", nickname: "Sophia Abrahão", image_url: "http://novaslistas.com.br/system/items/000/201/879/original/Sophia-Abrah_o.jpg?1386021095", categories:[categoria])
Candidate.create( name: "Juliana Paes", nickname: "Juliana Paes", image_url: "http://novaslistas.com.br/system/items/000/201/870/original/julyy.jpg?1386021095", categories:[categoria])
Candidate.create( name: "Hellen Ganzarolli", nickname: "Hellen Ganzarolli", image_url: "http://novaslistas.com.br/system/items/000/201/872/original/helen.jpg?1386021095", categories:[categoria])
Candidate.create( name: "Nathalia Dill", nickname: "Nathalia Dill", image_url: "http://imguol.com/c/entretenimento/2014/10/13/nathalia-dill-e-laura-na-novela-alto-astral-1413243002934_300x420.jpg", categories:[categoria])
Candidate.create( name: "Flavia Alessandra", nickname: "Flavia Alessandra", image_url: "http://imguol.com/c/entretenimento/2013/08/30/flavia-alessandra-1377896620968_1920x1080.jpg", categories:[categoria])
Candidate.create( name: "Sophie Charlotte", nickname: "Sophie Charlotte", image_url: "http://cdn.fstatic.com/public/artists/avatar/2014/04/thumbs/sophie-charlotte_a225690_3_jpg_640x480_upscale_q90.jpg", categories:[categoria])
Candidate.create( name: "Fernanda Machado", nickname: "Fernanda Machado", image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Fernandamachadobeach.jpg/250px-Fernandamachadobeach.jpg", categories:[categoria])
Candidate.create( name: "Mariana Ximenes", nickname: "Mariana Ximenes", image_url: "http://tv.i.uol.com.br/televisao/2010/11/08/para-a-atriz-mariana-ximenes-dar-vida-a-clara-de-passione-significa-estar-em-constante-mudanca-1289265349580_615x300.jpg", categories:[categoria])
Candidate.create( name: "Marina Ruy Barbosa", nickname: "Marina Ruy Barbosa", image_url: "http://fotos.caras.uol.com.br/media/images/mobile/2014/01/13/img-577227-marina-ruy-barbosa20140113151389632689.JPG", categories:[categoria])

Election.create(description: 'Qual é a atriz mais bonita?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)

categoria = Category.create(name: 'Ator')
Candidate.create( name: "Caio Castro", nickname: "Caio Castro", image_url: "http://capricho.abril.com.br/imagem/580x362/caio-castro40620.jpg", categories:[categoria])
Candidate.create( name: "Cauã Reymond", nickname: "Cauã Reymond", image_url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTXyWi8mJUE5VB-djgFcbEGaFBGc0eQq7mNeBeQwj60RjqzWg-L8g", categories:[categoria])
Candidate.create( name: "Bruno Gagliasso", nickname: "Bruno Gagliasso", image_url: "http://imagens.revoltabrasil.com.br/2014/06/gagi.jpg", categories:[categoria])
Candidate.create( name: "Reynaldo Gianecchini", nickname: "Reynaldo Gianecchini", image_url: "http://otvfoco.com.br/wp-content/uploads/2014/10/reynaldo-gianecchini_reproducao_abril.jpg", categories:[categoria])
Candidate.create( name: "Marcio Garcia", nickname: "Marcio Garcia", image_url: "http://diariodonordeste.verdesmares.com.br/polopoly_fs/1.1258799!/image/image.jpeg", categories:[categoria])
Candidate.create( name: "Rodrigo Santoro", nickname: "Rodrigo Santoro", image_url: "http://vejasp.abril.com.br/blogs/miguel-barbieri/files/2015/01/rodrigo_santoro_2013.jpg", categories:[categoria])
Candidate.create( name: "Henry Castelli", nickname: "Henry Castelli", image_url: "http://www.donamoda.com.br/wp-content/uploads/2013/05/tumblr-henri-castelli.jpg", categories:[categoria])
Candidate.create( name: "Malvino Salvador", nickname: "Malvino Salvador", image_url: "http://fotos.caras.uol.com.br/media/images/mobile/2011/06/17/img-300289-malvino-salvador.JPG", categories:[categoria])
Candidate.create( name: "José Loreto", nickname: "José Loreto", image_url: "http://blogs.ne10.uol.com.br/social1/files/2012/12/jose-loreto-30390.jpg", categories:[categoria])
Candidate.create( name: "Rodrigo Hilbert", nickname: "Rodrigo Hilbert", image_url: "http://mdemulher.abril.com.br/sites/mdemulher/files/styles/retangular_horizontal_2/public/migracao/rodrigo-hilbert-4971.jpg?itok=EBEjBMlL", categories:[categoria])
Candidate.create( name: "Rodrigo Lombardi", nickname: "Rodrigo Lombardi", image_url: "http://famososnaweb.com/wp-content/uploads/2015/05/Fanweb236.jpeg", categories:[categoria])
Candidate.create( name: "Daniel Rocha", nickname: "Daniel Rocha", image_url: "http://cdn.wp.clicrbs.com.br/julianawosgraus/files/2015/01/Daniel-Rocha-foto-Ro-Reitz-redred.jpg", categories:[categoria])
Candidate.create( name: "Marcos Mion", nickname: "Marcos Mion", image_url: "http://s2.glbimg.com/pKOb4O573mw6lfKkGcCPlu1st5BQ9iZw6lTXhHj2bWdIoz-HdGixxa_8qOZvMp3w/e.glbimg.com/og/ed/f/original/2013/11/29/mion-1.jpg", categories:[categoria])
Candidate.create( name: "Otaviano Costa", nickname: "Otaviano Costa", image_url: "http://br.web.img1.acsta.net/pictures/13/12/05/13/22/311695.jpg", categories:[categoria])
Candidate.create( name: "Caio Blat", nickname: "Caio Blat", image_url: "http://www.estadaoalagoas.com.br/wp-content/uploads/2014/06/caio-blat-10.jpg", categories:[categoria])
Candidate.create( name: "Romulo Neto", nickname: "Romulo Neto", image_url: "http://fotos.caras.uol.com.br/media/images/large/2014/07/30/img-622331-romulo-neto-e-cleo-pires20140730131406737936.jpg", categories:[categoria])
Candidate.create( name: "Wagner Moura", nickname: "Wagner Moura", image_url: "http://cdn.fstatic.com/public/artists/avatar/2013/03/thumbs/wagner-moura_a24125_1_jpg_640x480_upscale_q90.jpg", categories:[categoria])
Candidate.create( name: "Chai Suede", nickname: "Chai Suede", image_url: "http://mdemulher.abril.com.br/sites/mdemulher/files/migracao_body/791877/chay-suede-71723.jpg", categories:[categoria])
Candidate.create( name: "Guilherme Laicam", nickname: "Guilherme Laicam", image_url: "http://capricho.abril.com.br/imagem/580x362/guilherme-leicam40623.jpg", categories:[categoria])
Candidate.create( name: "Thiago Lacerda", nickname: "Thiago Lacerda", image_url: "http://fotos.caras.uol.com.br/media/images/raw/2014/09/10/img-631007-thiago-lacerda20140910201410390669.jpg", categories:[categoria])
Candidate.create( name: "Bruno Gissoni", nickname: "Bruno Gissoni", image_url: "http://capricho.abril.com.br/imagem/580x362/bruno-gissoni40622.jpg", categories:[categoria])

Election.create(description: 'Qual é o ator mais bonito?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)

categoria = Category.create(name: 'Kpop - Feminino')
Candidate.create( name: "Taeyeon", nickname: "Taeyeon", image_url: "http://www.soompi.com/br/wp-content/blogs.dir/9/files/2013/08/Taeyeon.jpg", categories:[categoria])
Candidate.create( name: "Tiffany", nickname: "Tiffany", image_url: "https://s-media-cache-ak0.pinimg.com/236x/93/86/2e/93862e0ffcdf84947a9aad8f12f38a2b.jpg", categories:[categoria])
Candidate.create( name: "Sunny", nickname: "Sunny", image_url: "http://images5.fanpop.com/image/photos/25800000/SNSD-The-Boys-2nd-Teaser-kpop-25887895-640-360.jpg", categories:[categoria])
Candidate.create( name: "Amber", nickname: "Amber", image_url: "https://soratothamax.files.wordpress.com/2014/02/large.jpg", categories:[categoria])
Candidate.create( name: "Krystal", nickname: "Krystal", image_url: "http://kpopnow.com.br/wp-content/uploads/2013/05/20130508_krystal-600x337.jpg", categories:[categoria])
Candidate.create( name: "Sully", nickname: "Sully", image_url: "https://s-media-cache-ak0.pinimg.com/236x/2c/73/de/2c73de0e6f38c27dbe03faf483a88917.jpg", categories:[categoria])
Candidate.create( name: "Yoona", nickname: "Yoona", image_url: "http://blog.kpopstage.co/wp-content/uploads/2013/07/tumblr_lzwkgw4OMU1qb9sxko1_500_large-500x325.png", categories:[categoria])
Candidate.create( name: "Hani", nickname: "Hani", image_url: "http://kpopconcerts.com/wp-content/uploads/2012/02/EXID-17.jpg", categories:[categoria])
Candidate.create( name: "Hyolin", nickname: "Hyolin", image_url: "http://www.billboard.com/files/styles/promo_650/public/media/sistar-3-650-430.jpg", categories:[categoria])
Candidate.create( name: "Bora", nickname: "Bora", image_url: "http://img.ohkpop.com/2013/02/01/XO87hb61.jpg", categories:[categoria])
Candidate.create( name: "Boa", nickname: "Boa", image_url: "http://falacultura.com/wp-content/uploads/2013/05/boa.jpg", categories:[categoria])
Candidate.create( name: "Nana", nickname: "Nana", image_url: "https://s-media-cache-ak0.pinimg.com/236x/5c/83/be/5c83be2908fe0321c418236e3181135b.jpg", categories:[categoria])
Candidate.create( name: "Hyosung", nickname: "Hyosung", image_url: "http://img.ohkpop.com/2013/05/07/UF47Tw36.jpg", categories:[categoria])
Candidate.create( name: "Hyoyeon", nickname: "Hyoyeon", image_url: "https://s-media-cache-ak0.pinimg.com/736x/2e/59/5a/2e595a075b9293fee668f2013cf55eb4.jpg", categories:[categoria])
Candidate.create( name: "CL", nickname: "CL", image_url: "http://images.au.kpopstarz.com/data/images/full/16831/cl.jpg", categories:[categoria])
Candidate.create( name: "Park bom", nickname: "Park bom", image_url: "http://images5.fanpop.com/image/photos/32000000/Park-Bom-yg-k-pop-battle-of-the-bands-32023652-1280-936.jpg", categories:[categoria])
Candidate.create( name: "Minzy", nickname: "Minzy", image_url: "http://img.ohkpop.com/2013/05/09/BP85GC67.jpg", categories:[categoria])

Election.create(description: 'Qual é a melhor cantora de Kpop?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)

categoria = Category.create(name: 'Kpop - Masculino')
Candidate.create( name: "Siwon", nickname: "Siwon", image_url: "https://s-media-cache-ak0.pinimg.com/236x/cd/f4/07/cdf40798a623b41163f80f2c777c7115.jpg", categories:[categoria])
Candidate.create( name: "Donghae", nickname: "Donghae", image_url: "http://images6.fanpop.com/image/photos/33200000/Donghae-kpop-4ever-33285089-491-392.jpg", categories:[categoria])
Candidate.create( name: "Heechul", nickname: "Heechul", image_url: "https://s-media-cache-ak0.pinimg.com/236x/66/1a/a0/661aa0ba5e9a719747ba7c7ef6464bcc.jpg", categories:[categoria])
Candidate.create( name: "Jonghyun ( shinee)", nickname: "Jonghyun ( shinee)", image_url: "http://s3.favim.com/orig/40/jjong-jonghyun-korean-kpop-shinee-Favim.com-340163.jpg", categories:[categoria])
Candidate.create( name: "Key", nickname: "Key", image_url: "http://s1.favim.com/orig/24/almighty-key-key-kim-kibum-korean-kpop-Favim.com-220157.jpg", categories:[categoria])
Candidate.create( name: "Kai", nickname: "Kai", image_url: "https://s-media-cache-ak0.pinimg.com/236x/16/90/26/169026ffe103253ad5741957bd0a6843.jpg", categories:[categoria])
Candidate.create( name: "D.o", nickname: "D.o", image_url: "http://29.media.tumblr.com/tumblr_m3morjU6fK1rsaba2o1_500.jpg", categories:[categoria])
Candidate.create( name: "Tao", nickname: "Tao", image_url: "http://s9.favim.com/orig/130909/exo-exo-m-exo-m-kpop-Favim.com-911223.jpg", categories:[categoria])
Candidate.create( name: "Baekhyun", nickname: "Baekhyun", image_url: "http://images6.fanpop.com/image/photos/33300000/Baekhyun-EXO-K-kpop-4ever-33365250-400-240.png", categories:[categoria])
Candidate.create( name: "Ryeowook", nickname: "Ryeowook", image_url: "https://s-media-cache-ak0.pinimg.com/236x/05/84/57/05845796ea6746bcb791fc42d9c86d06.jpg", categories:[categoria])
Candidate.create( name: "Henry", nickname: "Henry", image_url: "http://www.allkpop.com/upload/2014/04/af_org/henry_1397573162_af_org.jpg", categories:[categoria])
Candidate.create( name: "Zhoumi", nickname: "Zhoumi", image_url: "https://s-media-cache-ak0.pinimg.com/236x/7c/dd/94/7cdd9463465ec942bc5b965a19a1764a.jpg", categories:[categoria])
Candidate.create( name: "Jong up", nickname: "Jong up", image_url: "http://4.bp.blogspot.com/-ZmWqeu4GnrE/UQPbI10RpMI/AAAAAAAAAM0/nyn6fSjXbXg/s1600/bap-pic29-jong_up.jpg", categories:[categoria])
Candidate.create( name: "Daehyun", nickname: "Daehyun", image_url: "http://images6.fanpop.com/image/photos/33300000/-Daehyun-Rain-Sound-MV-kpop-4ever-33315179-1280-720.jpg", categories:[categoria])
Candidate.create( name: "Zico", nickname: "Zico", image_url: "http://www.jpopasia.com/i1/celebrities/1/28031-zico-3xtf.jpg", categories:[categoria])
Candidate.create( name: "Rap monster", nickname: "Rap monster", image_url: "http://inspirekpop.com/wp-content/uploads/2015/02/Bangtan-Boys-image-bangtan-boys-36591680-1482-797.jpg", categories:[categoria])
Candidate.create( name: "Taec yeon", nickname: "Taec yeon", image_url: "https://s-media-cache-ak0.pinimg.com/236x/b9/3d/07/b93d0777cbbc6cf0db387ec1efe728cd.jpg", categories:[categoria])
Candidate.create( name: "Taemin", nickname: "Taemin", image_url: "http://4.bp.blogspot.com/-1IZzyNQkDwM/UBrMInYn2UI/AAAAAAAACb4/sGhwLCy7SK4/s1600/Shinee-Taemin-Immortal-Song-2.jpg", categories:[categoria])
Candidate.create( name: "Yunho ( u kwon)", nickname: "Yunho ( u kwon)", image_url: "http://www.jpopasia.com/i1/news/4/15835-fp41mppo1m.jpg", categories:[categoria])
Candidate.create( name: "Changmin max", nickname: "Changmin max", image_url: "https://s-media-cache-ak0.pinimg.com/236x/97/d6/31/97d631f3ee3e29ec9a80042e4548a0b4.jpg", categories:[categoria])
Candidate.create( name: "Gdragon", nickname: "Gdragon", image_url: "http://images4.fanpop.com/image/photos/22900000/G-Dragon-men-of-kpop-22914485-250-329.jpg", categories:[categoria])
Candidate.create( name: "TOP", nickname: "TOP", image_url: "http://images6.fanpop.com/image/photos/33100000/TOP-kpop-33148882-500-578.jpg", categories:[categoria])
Candidate.create( name: "Seungri", nickname: "Seungri", image_url: "http://media.tumblr.com/tumblr_mbk00py2Qy1rx77hs.jpg", categories:[categoria])
Candidate.create( name: "Jimin", nickname: "Jimin", image_url: "http://images6.fanpop.com/image/photos/36600000/Kpop-Vocalist-image-kpop-vocalist-36670917-500-565.jpg", categories:[categoria])
Candidate.create( name: "Dongwoo", nickname: "Dongwoo", image_url: "https://picahpicah.files.wordpress.com/2013/04/20130415-114227.jpg", categories:[categoria])
Candidate.create( name: "Eunhyuk", nickname: "Eunhyuk", image_url: "http://images5.fanpop.com/image/photos/25200000/Eunhyuk-in-Mr-Simple-kpop-channel-25287671-854-480.jpg", categories:[categoria])
Candidate.create( name: "P.o", nickname: "P.o", image_url: "http://img.ohkpop.com/2012/02/24/wV87SA36.jpg", categories:[categoria])
Candidate.create( name: "Youngjae", nickname: "Youngjae", image_url: "https://s-media-cache-ak0.pinimg.com/236x/26/69/d3/2669d32992115748201a7aaafb608e3a.jpg", categories:[categoria])
Candidate.create( name: "Jaejoong", nickname: "Jaejoong", image_url: "http://images6.fanpop.com/image/photos/35800000/JYJ-Jaejoong-kpop-vocalist-35895959-620-413.jpg", categories:[categoria])

Election.create(description: 'Qual é o melhor cantor de Kpop?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)

categoria = Category.create(name: 'Times Brasileiros')
Candidate.create( name: "América - Belo Horizonte MG", nickname: "América-MG", image_url: "http://aimore.org/escudos/America_MG.jpg", categories:[categoria])
Candidate.create( name: "Atlético Clube Goianiense", nickname: "Atlético-GO", image_url: "http://aimore.org/escudos/Atletico_Goianiense.jpg", categories:[categoria])
Candidate.create( name: "Clube Atlético Mineiro", nickname: "Atlético-MG", image_url: "http://aimore.org/escudos/Atletico_Mineiro.jpg", categories:[categoria])
Candidate.create( name: "Clube Atlético Paranaense", nickname: "Atlético-PR", image_url: "http://aimore.org/escudos/Atletico_Paranaense.jpg", categories:[categoria])
Candidate.create( name: "Avaí Futebol Clube", nickname: "Avaí", image_url: "http://aimore.org/escudos/Avai.jpg", categories:[categoria])
Candidate.create( name: "Esporte Clube Bahia", nickname: "Bahia", image_url: "http://aimore.org/escudos/Bahia.jpg", categories:[categoria])
Candidate.create( name: "Boa Esporte Clube", nickname: "Boa Esporte", image_url: "http://aimore.org/escudos/Boa_EC_Varginha.jpg", categories:[categoria])
Candidate.create( name: "Botafogo de Futebol e Regatas", nickname: "Botafogo", image_url: "http://aimore.org/escudos/Botafogo_RJ.jpg", categories:[categoria])
Candidate.create( name: "Clube Atlético Bragantino", nickname: "Bragantino", image_url: "http://aimore.org/escudos/Bragantino.jpg", categories:[categoria])
Candidate.create( name: "Ceará Sporting Club", nickname: "Ceará", image_url: "http://aimore.org/escudos/Ceara.jpg", categories:[categoria])
Candidate.create( name: "Associação Chapecoense de Futebol", nickname: "Chapecoense", image_url: "http://aimore.org/escudos/Chapecoense_SC.jpg", categories:[categoria])
Candidate.create( name: "Sport Club Corinthians Paulista", nickname: "Corinthians", image_url: "http://aimore.org/escudos/Corinthians.jpg", categories:[categoria])
Candidate.create( name: "Coritiba Foot Ball Club", nickname: "Coritiba", image_url: "http://aimore.org/escudos/Coritiba.jpg", categories:[categoria])
Candidate.create( name: "CRB – Clube de Regatas Brasil", nickname: "CRB", image_url: "http://aimore.org/escudos/CRB.jpg", categories:[categoria])
Candidate.create( name: "Criciúma Esporte Clube", nickname: "Criciúma", image_url: "http://aimore.org/escudos/Criciuma.jpg", categories:[categoria])
Candidate.create( name: "Cruzeiro Esporte Clube", nickname: "Cruzeiro", image_url: "http://aimore.org/escudos/Cruzeiro.jpg", categories:[categoria])
Candidate.create( name: "Figueirense Futebol Clube", nickname: "Figueirense", image_url: "http://aimore.org/escudos/Figueirense.jpg", categories:[categoria])
Candidate.create( name: "Clube de Regatas do Flamengo", nickname: "Flamengo", image_url: "http://aimore.org/escudos/Flamengo.jpg", categories:[categoria])
Candidate.create( name: "Fluminense Football Club", nickname: "Fluminense", image_url: "http://aimore.org/escudos/Fluminense.jpg", categories:[categoria])
Candidate.create( name: "Goiás Esporte Clube", nickname: "Goiás", image_url: "http://aimore.org/escudos/Goias.jpg", categories:[categoria])
Candidate.create( name: "Grêmio Foot-Ball Porto Alegrense", nickname: "Grêmio", image_url: "http://aimore.org/escudos/Gremio.jpg", categories:[categoria])
Candidate.create( name: "Sport Club Internacional", nickname: "Internacional", image_url: "http://aimore.org/escudos/Internacional.jpg", categories:[categoria])
Candidate.create( name: "Joinville Esporte Clube", nickname: "Joinville", image_url: "http://aimore.org/escudos/Joinville.jpg", categories:[categoria])
Candidate.create( name: "Luverdense Esporte Clube", nickname: "Luverdense", image_url: "http://aimore.org/escudos/Luverdense_EC.png", categories:[categoria])
Candidate.create( name: "Macaé Esporte Futebol Clube", nickname: "Macaé", image_url: "http://aimore.org/escudos/Macae_RJ.png", categories:[categoria])
Candidate.create( name: "Clube Náutico Capibaribe", nickname: "Náutico", image_url: "http://aimore.org/escudos/Nautico.jpg", categories:[categoria])
Candidate.create( name: "Oeste Futebol Clube", nickname: "Oeste", image_url: "http://aimore.org/escudos/Oeste_FC_Itapolis.jpg", categories:[categoria])
Candidate.create( name: "Sociedade Esportiva Palmeiras", nickname: "Palmeiras", image_url: "http://aimore.org/escudos/Palmeiras.jpg", categories:[categoria])
Candidate.create( name: "Paraná Clube", nickname: "Paraná", image_url: "http://aimore.org/escudos/Parana_Clube.jpg", categories:[categoria])
Candidate.create( name: "Paysandu Sport Club", nickname: "Paysandu", image_url: "http://aimore.org/escudos/Paysandu.jpg", categories:[categoria])
Candidate.create( name: "Associação Atlética Ponte Preta", nickname: "Ponte Preta", image_url: "http://aimore.org/escudos/Ponte_Preta.jpg", categories:[categoria])
Candidate.create( name: "Sampaio Corrêa", nickname: "Sampaio Corrêa", image_url: "http://aimore.org/escudos/Sampaio_Correa_MA.jpg", categories:[categoria])
Candidate.create( name: "Santa Cruz Futebol Clube", nickname: "Santa Cruz", image_url: "http://aimore.org/escudos/Santa_Cruz.jpg", categories:[categoria])
Candidate.create( name: "Santos Futebol Clube", nickname: "Santos", image_url: "http://aimore.org/escudos/Santos.jpg", categories:[categoria])
Candidate.create( name: "São Paulo Futebol Clube", nickname: "São Paulo", image_url: "http://aimore.org/escudos/Sao_Paulo.jpg", categories:[categoria])
Candidate.create( name: "Sport Club do Recife", nickname: "Sport", image_url: "http://aimore.org/escudos/Sport_Recife.jpg", categories:[categoria])
Candidate.create( name: "Club de Regatas Vasco da Gama", nickname: "Vasco", image_url: "http://aimore.org/escudos/Vasco.jpg", categories:[categoria])
Candidate.create( name: "Esporte Clube Vitória", nickname: "Vitória", image_url: "http://aimore.org/escudos/Vitoria.jpg", categories:[categoria])

Election.create(description: 'Qual é o melhor time do Brasil?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)

categoria = Category.create(name: 'Anime')
Candidate.create( name: "Nisekoi 2", nickname: "Nisekoi 2", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Nisekoi-2nd-season-visual-322x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Show by Rock", nickname: "Show by Rock", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Show-by-Rock-322x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Ore Monogatari!!", nickname: "Ore Monogatari!!", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Ore-Monogatari-317x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Triage X", nickname: "Triage X", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Ore-Monogatari-317x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Houkago no Pleaides", nickname: "Houkago no Pleaides", image_url: "http://www.animexis.com.br/wp-content/uploads/2014/09/triage-x--450x316.jpg?266208", categories:[categoria])
Candidate.create( name: "Sidonia no Kishi: Daikyuu Wakusei Seneki", nickname: "Sidonia no Kishi: Daikyuu Wakusei Seneki", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/01/Houkago-no-Pleiades-imagem-450x326.jpg?266208", categories:[categoria])
Candidate.create( name: "OreGairu.Zoku", nickname: "OreGairu.Zoku", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Sidonia-no-Kishi-319x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Nagato Yuki-Chan no Shoushitsu", nickname: "Nagato Yuki-Chan no Shoushitsu", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/OreGairu-visual-2.jpg?266208", categories:[categoria])
Candidate.create( name: "Nisekoi 2", nickname: "Nisekoi 2", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Nagato-Yuki-chan-no-Shoushitsu-visual-novo-310x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Plastic Memories", nickname: "Plastic Memories", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Plastic-Memories-303x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Hibike! Euphonium", nickname: "Hibike! Euphonium", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Hibike-Euphonium-01-450x433.jpg?266208", categories:[categoria])
Candidate.create( name: "Gunslinger Stratos", nickname: "Gunslinger Stratos", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/04/Temporada-de-Primavera-2015-Gunslinger-Stratos-318x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Re-Kan!", nickname: "Re-Kan!", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/04/Re-Kan-300x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Dungeon ni Deai o Motomeru no wa Machigatteiru no Darō ka?", nickname: "Dungeon ni Deai o Motomeru no wa Machigatteiru no Darō ka?", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Dungeon-ni-Deai-wo-Motomeru-no-wa-Machigatteiru-no-Darou-ka-316x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Kekkai Sensen", nickname: "Kekkai Sensen", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/kekkai-sensen-450x324.jpg?266208", categories:[categoria])
Candidate.create( name: "Owari no Seraph", nickname: "Owari no Seraph", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Owari-no-Seraph-311x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Shokugeki no Souma", nickname: "Shokugeki no Souma", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Shokugeki-no-Souma-image-01-450x360.jpg?266208", categories:[categoria])
Candidate.create( name: "Fate/Stay Night: Unlimited Blade Works 2015", nickname: "Fate/Stay Night: Unlimited Blade Works 2015", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Fate-Stay-Night-UBW-2015-visual-346x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Punch Line", nickname: "Punch Line", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/02/Primavera-2015-Punchline-319x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Ghost in The Shell Arise: Alternative Architecture", nickname: "Ghost in The Shell Arise: Alternative Architecture", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Ghost-in-the-Shell-Arise-319x450.jpg?266208", categories:[categoria])
Candidate.create( name: "Arslan Senki", nickname: "Arslan Senki", image_url: "http://www.animexis.com.br/wp-content/uploads/2015/03/Arslan-Senki-321x450.jpg?266208", categories:[categoria])
Candidate.create( name: " Psycho-Pass", nickname: " Psycho-Pass", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/psycho-pass-review-3.jpg", categories:[categoria])
Candidate.create( name: "Tengen Toppa Gurren Lagann", nickname: "Tengen Toppa Gurren Lagann", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/tengen-toppa-gurren-lagann-full-604928.jpg", categories:[categoria])
Candidate.create( name: " Suisei no Gargantia", nickname: " Suisei no Gargantia", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/amy-suisei-no-gargantia-wallpaper-verdurous-planet-flying.jpg", categories:[categoria])
Candidate.create( name: "Haibane Renmei", nickname: "Haibane Renmei", image_url: "http://wrongeverytime.com/wp-content/uploads/2014/03/haibane.jpg", categories:[categoria])
Candidate.create( name: "Gatchaman Crowds", nickname: "Gatchaman Crowds", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/gatchaman-crowds-op-large-03.jpg", categories:[categoria])
Candidate.create( name: "Steins;Gate", nickname: "Steins;Gate", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/345052.jpg", categories:[categoria])
Candidate.create( name: "Chuunibyou demo Koi ga Shitai", nickname: "Chuunibyou demo Koi ga Shitai", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/gg_chuunibyou_demo_koi_ga_shitai_-_10_dd9540f4_dec-6-2012-9-30-58-pm.jpg", categories:[categoria])
Candidate.create( name: "Spice and Wolf", nickname: "Spice and Wolf", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/20874_spice_and_wolf.jpg", categories:[categoria])
Candidate.create( name: "Hunter x Hunter 2011", nickname: "Hunter x Hunter 2011", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/horriblesubs-hunter-x-hunter-112-720p-mkv_snapshot_12-28_2014-01-15_22-43-151.jpg", categories:[categoria])
Candidate.create( name: "Mushishi", nickname: "Mushishi", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/mushishi-wall-mushi-shi-16650576-1600-1200.jpg", categories:[categoria])
Candidate.create( name: "Gunbuster! + Diebuster!", nickname: "Gunbuster! + Diebuster!", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/gunbuster-vs-diebuster.jpg", categories:[categoria])
Candidate.create( name: "Shinsekai Yori", nickname: "Shinsekai Yori", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/shinsekai_yori_u01.jpg", categories:[categoria])
Candidate.create( name: "Hyouka", nickname: "Hyouka", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/hyouka-hyouka-33487324-1280-720.png", categories:[categoria])
Candidate.create( name: "Toradora!", nickname: "Toradora!", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/toradora-full-1181972.jpg", categories:[categoria])
Candidate.create( name: "Kids on the Slope", nickname: "Kids on the Slope", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/965648.jpg", categories:[categoria])
Candidate.create( name: "Shiki", nickname: "Shiki", image_url: "http://wrongeverytime.files.wordpress.com/2014/05/elysiumshiki-ep03bd-720p-hi10p-aace6a3a994-mkv_snapshot_21-10_2014-05-25_15-14-44.jpg", categories:[categoria])
Candidate.create( name: "Kyousogiga", nickname: "Kyousogiga", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/541958.jpg", categories:[categoria])
Candidate.create( name: "Cowboy Bebop", nickname: "Cowboy Bebop", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/cowboy_bebop_desktop_1024x768_wallpaper-276818.jpg", categories:[categoria])
Candidate.create( name: "Ping Pong The Animation", nickname: "Ping Pong The Animation", image_url: "http://wrongeverytime.files.wordpress.com/2014/06/horriblesubs-ping-pong-the-animation-02-720p-mkv_snapshot_16-19_2014-06-21_14-00-39.jpg", categories:[categoria])
Candidate.create( name: "Kino’s Journey", nickname: "Kino’s Journey", image_url: "http://wrongeverytime.files.wordpress.com/2014/03/72592.jpg", categories:[categoria])
Candidate.create( name: "Shirobako", nickname: "Shirobako", image_url: "http://wrongeverytime.com/wp-content/uploads/2015/04/HorribleSubs-Shirobako-24-720p.mkv_snapshot_22.21_2015.03.28_19.40.51.jpg", categories:[categoria])
Candidate.create( name: "Dragon Ball", nickname: "Dragon Ball", image_url: "http://2.bp.blogspot.com/-6NyPNQJuUDQ/UyD0XicjvPI/AAAAAAAAAnA/A3qjFngUKbw/s1600/1599632.jpg", categories:[categoria])
Candidate.create( name: "Cavaleiros do Zodíaco", nickname: "Cavaleiros do Zodíaco", image_url: "http://1.bp.blogspot.com/-ClFvjcaSAf4/UyDjnrqmrMI/AAAAAAAAAmQ/B5bU8tSuFO0/s1600/6636_render_kamuis_5.png", categories:[categoria])
Candidate.create( name: "Yu Yu Hakusho", nickname: "Yu Yu Hakusho", image_url: "http://1.bp.blogspot.com/-6jg8AwuILGE/UyC2dYJEx1I/AAAAAAAAAlE/8oTNvRETrfE/s1600/yuyu-hakusho-5.jpg", categories:[categoria])
Candidate.create( name: "Samurai X", nickname: "Samurai X", image_url: "http://1.bp.blogspot.com/-4DsUFCibJB4/UyCVwUKMJzI/AAAAAAAAAj8/uuU39j2MpXQ/s1600/kenshin_himura___samurai_x_wallpaper_by_yasuo07-d5wdxr3.jpg", categories:[categoria])
Candidate.create( name: "Digimon", nickname: "Digimon", image_url: "http://4.bp.blogspot.com/-USzx6lsa0DQ/UyB5hTob5dI/AAAAAAAAAjE/3v73rz_2biY/s1600/Digimon.Adventures.full_.1416033.jpg", categories:[categoria])
Candidate.create( name: "Pokémon", nickname: "Pokémon", image_url: "http://3.bp.blogspot.com/-5ZeL1F34CLg/UyBtfA3CTbI/AAAAAAAAAio/5rNvCqlqmlQ/s1600/Pokemon_Wallpaper_by_gamingaddictmike125.png", categories:[categoria])
Candidate.create( name: "YU-GI-OH", nickname: "YU-GI-OH", image_url: "http://1.bp.blogspot.com/-QinMRDmRiOU/Ux_U1HeButI/AAAAAAAAAgU/fGDTpR9AiRQ/s1600/classic_1_wallpaper_1280x800+(1).jpg", categories:[categoria])
Candidate.create( name: "Inuyasha", nickname: "Inuyasha", image_url: "http://4.bp.blogspot.com/-NVYmCoCQ46I/UyBf8VcAMDI/AAAAAAAAAiI/4Rrlgrp-yQo/s1600/InuYasha.(Character).full.1230954.jpg", categories:[categoria])

Election.create(description: 'Qual é o melhor anime?', start_date: 1.day.ago, finish_date: 1.year.from_now, status: '1', category: categoria)